### ISSUE TITLE
Are credentials required to view or work with the data? 

### ISSUE THREAD

**Issue by gwaybio** [WayScience/JUMP-single-cell#2]
If so, consider providing some mention about what credentials are used (in the broad sense) and how one might obtain permission to the data. If not, consider mentioning that this is publicly available data and possibly extend the code to use anonymous/unsigned mechanisms for reproducibility (and avoid awscli configurations).

_Originally posted by @d33bs in https://github.com/WayScience/JUMP-single-cell/pull/1#discussion_r1161984680_

**Comment by jenna-tomkinson** [comment]
@MattsonCam 

Do you happen to know if there are any code snippets you can add in the [download_data README](https://github.com/WayScience/JUMP-single-cell/tree/main/0.download_data) that would resolve this issue?

**Comment by MattsonCam** [comment]
I think this has been resolved with pr #25, so I'll close this issue
